export const LIST_PRODUCT_ON_CART = 'LIST_PRODUCT_ON_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const UPDATE_TO_CART = 'UPDATE_TO_CART';
export const GET_DATABASE_UPDATE = 'GET_DATABASE_UPDATE';